meta:
  engine: 4.1.0
units:
  units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 2
  py: ky + 2

  # demo output keysize
  $default_width: cx
  $default_height: cy

  # board padding (some points need manual correction for now)
  bp: 1


points:
  zones:
    matrix:
      anchor.shift: [50, -100]
      key:
        padding: 1ky
        spread: 1kx
      columns:
        outer:
          rows.bottom.skip: true
        pinky:
          key.stagger: ky / 2 - 2
        ring:
          key.stagger: 13
        middle:
          key.stagger: 5
        index:
          key.stagger: -6
        inner:
      rows:
        bottom:
        home:
        top:
    thumb:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        ref: matrix_inner_bottom
        shift: [-1/3kx, -ky-3]
      columns:
        near:
          key:
            splay: -10
        home:
          key:
            splay: -16
            shift: [4.5, -3]
        far:
          key:
            splay: -16
            shift: [9.5, -4.5]

  # # Mirror and rotate for preview:
  #
  # rotate: -25
  # mirror: &mirror
  #     ref: matrix_inner_bottom
  #     distance: 5kx


outlines:
  keys:
    - what: rectangle
      where: true
      # size: [kx,ky]
      size: [kx-0.1,ky-0.1]
      # size: [kx-0.5,ky-0.5]
  board:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_pinky_bottom
          shift: [0.5px+bp,-0.5py-bp]
        - ref: matrix_pinky_bottom
          shift: [-0.5px-bp,-0.5py-bp]
        - ref: matrix_outer_home
          shift: [0.5px-2-bp,-0.5py-bp]
        - ref: matrix_outer_home
          shift: [-0.5px-bp,-0.5py-bp]
        - ref: matrix_outer_top
          shift: [-0.5px-bp,0.5py+bp]
        - ref: matrix_outer_top
          shift: [0.5px-2-bp,0.5py+bp]
        - ref: matrix_pinky_top
          shift: [-0.5px-bp,0.5py+bp]
        - ref: matrix_pinky_top
          shift: [0.5px-2-bp,0.5py+bp]
        - ref: matrix_ring_top
          shift: [-0.5px-bp,0.5py+bp]
        - ref: matrix_ring_top
          shift: [0.5px-2-bp,0.5py+bp]
        - ref: matrix_middle_top
          shift: [-0.5px-bp,0.5py+bp]
        - ref: matrix_middle_top
          shift: [0.5px+bp,0.5py+bp]
        - ref: matrix_index_top
          shift: [-0.5px+2+bp,0.5py+bp]
        - ref: matrix_inner_top
          shift: [1.80px,0.5py+bp]
        - ref: matrix_inner_bottom
          shift: [1.80px,-0.5py-bp]
        # - ref: thumb_far
        #   shift: [-0.5px-bp,0.5px+bp+7.6]
        - ref: thumb_far
          shift: [0.5px+bp,0.5py+bp]
        - ref: thumb_far
          shift: [0.5px+bp,-0.5py-bp]
        - ref: thumb_far
          shift: [-0.5px-bp,-0.5py-bp]
        - ref: thumb_home
          shift: [-0.5px-bp,-0.5py-bp]
        - ref: thumb_near
          shift: [-0.5px-bp,-0.5py-bp]
        - ref: matrix_pinky_bottom
          shift: [3kx-bp,-0.5py-bp]
      fillet: 2
  combo:
    - name: board
    # - operation: add
    - operation: subtract
      name: keys


pcbs:
  oregano:
    template: kicad8
    outlines:
      main:
        outline: board
    footprints:
      
      choc_hotswap:
        what: switch_choc_v1_v2
        where: true
        params:
          # default (but important)
          hotswap: true
          include_traces_vias: true
          # modified
          from: "{{column_net}}"
          to: "{{colrow}}"
          choc_v2_support: false
          include_corner_marks: true
          reversible: true
          solder: true
          hotswap_pads_same_side: true
          include_keycap: true
          keycap_height: 17
      
      diode:
        what: diode_tht_sod123
        where: true
        params:
          reversible: true
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -3.4]
      
      diode-key-route: # TODO
        what: utility_router
        where: true
        params:
          # route: "f(-5.842 -5.08) (-6.5 -4) (-6.5 2) (-6 2.5) (1.2 2.5) (1.7 3) (1.7 5)"

      mcu:
        what: mcu_supermini_nrf52840
        where:
          ref: matrix_inner_top
          shift: [21,-8]
        params:
          reversible: true
          reverse_mount: true
          show_instructions: true
      
      display:
        what: display_nice_view
        where:
          ref: matrix_inner_top
          shift: [21,-8-3.5]
        params:
          reversible: true
          invert_jumpers_position: true
          MOSI: "DA"
          SCK: "CL"

      reset:
        what: wuerth-434121025816 
        params:
          r1: RST
          r2: GND
        where:
          ref: matrix_inner_top
          shift: [17, -40]
          rotate: -90

        
cases:
